[package]
name = "rpc"
version = "0.1.0"
edition = "2024"

[features]
default = ["quali-crypt"]
quali-crypt = [
    "dep:aes",
    "dep:bytes",
    "dep:cbc",
    "dep:flate2",
    "dep:http-body",
    "dep:http-body-util",
    "dep:md-5",
    "dep:tower",
]

[dependencies]
parking_lot.workspace = true
prost.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true

aes = { workspace = true, optional = true }
cbc = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
md-5 = { workspace = true, optional = true }
rand.workspace = true

bytes = { workspace = true, optional = true }
http-body = { workspace = true, optional = true }
http-body-util = { workspace = true, optional = true }
tower = { workspace = true, optional = true }

resource.workspace = true
types.workspace = true
