[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
resource.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-debug.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
types.workspace = true
serde.workspace = true
serde_json.workspace = true
